/**
 * POST /api/webhooks/bounce
 * US-472: Postmark (and SendGrid-compatible) bounce webhook handler.
 *
 * Processes inbound bounce/complaint notifications from the email provider
 * and writes them to `email_suppression_list` via `addSuppression`.
 *
 * Postmark event types handled:
 *   - HardBounce     → suppress permanently
 *   - SpamComplaint  → suppress permanently
 *   - SoftBounce     → record only (not suppressed; provider will retry)
 *   - Unsubscribe    → suppress (generated by provider List-Unsubscribe header)
 *
 * SendGrid inbound events are structurally different but share the same
 * field semantics — the normalizer handles both.
 *
 * Authentication: BOUNCE_WEBHOOK_SECRET header check.
 * Must be excluded from auth middleware (arrives unauthenticated from provider).
 * Added to PUBLIC_PATHS in middleware.ts as /api/webhooks.
 */

import { NextRequest, NextResponse } from "next/server";
import { addSuppression }            from "@/lib/email/suppression";
import { createServiceClient }       from "@/lib/supabase/service";
import crypto                        from "node:crypto";

// ── Postmark event types that require suppression ──────────────────────────

const SUPPRESS_TYPES = new Set(["HardBounce", "SpamComplaint", "Unsubscribe"]);

// ── Normalised event shape ─────────────────────────────────────────────────

interface NormalisedBounce {
  email:     string;
  eventType: "HardBounce" | "SoftBounce" | "SpamComplaint" | "Unsubscribe" | "Other";
  messageId?: string;
  domainId?:  string;   // provider domain identifier to resolve agency
}

function normalisePostmark(body: Record<string, unknown>): NormalisedBounce | null {
  const email = (body.Email ?? body.Recipient ?? body.To) as string | undefined;
  if (!email || typeof email !== "string") return null;

  const rawType = (body.Type ?? body.RecordType ?? "") as string;

  const eventType: NormalisedBounce["eventType"] =
    rawType === "HardBounce"    ? "HardBounce" :
    rawType === "SoftBounce"    ? "SoftBounce" :
    rawType === "SpamComplaint" ? "SpamComplaint" :
    rawType === "Unsubscribe"   ? "Unsubscribe" :
    "Other";

  return {
    email:     email.toLowerCase(),
    eventType,
    messageId: (body.MessageID ?? body.ID) as string | undefined,
  };
}

// ── Route handler ──────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  // Verify secret header (set in Postmark/SendGrid webhook settings)
  const secret = process.env.BOUNCE_WEBHOOK_SECRET;
  if (secret) {
    const headerSecret = req.headers.get("x-bounce-webhook-secret") ??
                         req.headers.get("x-postmark-secret") ?? "";
    const expected = crypto
      .createHmac("sha256", secret)
      .update(headerSecret)
      .digest("hex");
    // Simple equality check — secret is in the header directly for Postmark
    if (headerSecret !== secret) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
  }

  let bodyRaw: unknown;
  try {
    bodyRaw = await req.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  // Postmark sends either a single object or an array of events
  const events: Record<string, unknown>[] = Array.isArray(bodyRaw)
    ? bodyRaw as Record<string, unknown>[]
    : [bodyRaw as Record<string, unknown>];

  const supabase = createServiceClient();
  let processed = 0;

  for (const event of events) {
    const normalised = normalisePostmark(event);
    if (!normalised) continue;

    // Attempt to resolve agency from the sending domain
    let agencyId: string | null = null;

    // Try matching by message domain (from domain field in event payload)
    const fromEmail = (event.From ?? event.FromEmail ?? "") as string;
    if (fromEmail && fromEmail.includes("@")) {
      const fromDomain = fromEmail.split("@")[1]?.toLowerCase();
      if (fromDomain) {
        const { data: domainRow } = await supabase
          .from("sending_domains")
          .select("agency_id")
          .eq("domain", fromDomain)
          .maybeSingle();
        agencyId = domainRow?.agency_id ?? null;
      }
    }

    if (!agencyId) {
      // Skip — can't attribute bounce to an agency without domain context
      console.warn("[bounce-webhook] cannot resolve agency for", normalised.email);
      continue;
    }

    // Record bounce in email_bounces
    if (normalised.eventType !== "Other") {
      const bounceType =
        normalised.eventType === "HardBounce"    ? "hard" :
        normalised.eventType === "SoftBounce"    ? "soft" :
        normalised.eventType === "SpamComplaint" ? "complaint" :
        "unknown";

      await supabase.from("email_bounces").insert({
        agency_id:       agencyId,
        recipient_email: normalised.email,
        bounce_type:     bounceType,
        message_id:      normalised.messageId ?? null,
        dsn_raw:         event,
      }).catch(err => console.error("[bounce-webhook] bounce insert failed", err));
    }

    // Suppress if it's a hard type
    if (SUPPRESS_TYPES.has(normalised.eventType)) {
      const reason =
        normalised.eventType === "SpamComplaint" ? "spam_complaint" :
        normalised.eventType === "Unsubscribe"   ? "unsubscribe" :
        "bounce_hard";

      await addSuppression({
        agencyId,
        email:    normalised.email,
        reason,
        messageId: normalised.messageId,
        source:   "webhook:postmark",
      }).catch(err => console.error("[bounce-webhook] suppression failed", err));
    }

    processed++;
  }

  return NextResponse.json({ processed });
}
