/**
 * lib/ai/decision-log.ts (US-422)
 *
 * Records one row in `ai_decisions` per user-meaningful AI decision.
 * Complements `ai_usage_events` (raw API-call log) with a layer the
 * candidate-portal transparency view and the admin dashboard can consume
 * directly.
 *
 * Design contract:
 *   - Fire-and-forget. Never throws, never blocks the caller's request.
 *     (The primary operation already succeeded by the time we log the
 *     decision; a logging failure must not surface to the user.)
 *   - Uses the service client so decisions are written even when RLS
 *     context hasn't been established (e.g. cron workers).
 *   - Deliberately thin: subject/related pointers only, no raw prompt
 *     storage. PII stays in its original table; `input_hash` provides
 *     reproducibility without retention risk.
 *
 * EU AI Act alignment: every automated decision that can shape a
 * candidate's outcome carries a stable model identity (`provider`,
 * `model`, `model_card_url`), a short human-readable rationale, and
 * a timestamp — satisfying the logging baseline.
 */

import { createServiceClient } from "@/lib/supabase/service";
import { createHash } from "crypto";

/* ── Types ────────────────────────────────────────────────────────────── */

/**
 * All supported decision types. Adding a new one? Also add an entry to
 * MODEL_CARDS so the admin/transparency UI can link to documentation.
 */
export type DecisionType =
  | "match_score_embedding"      // vector cosine ranking (US-382)
  | "match_score_explain"        // LLM breakdown + rationale (US-110)
  | "resume_parse"               // PDF/DOCX extraction (US-031/US-380)
  | "skill_normalise"            // canonicalise skill strings (US-381)
  | "candidate_summary"          // AI bio summary
  | "candidate_outreach"         // AI-drafted outreach message
  | "interview_questions"        // prep questions generated by AI
  | "shortlist_compile"          // ranked shortlist + per-candidate blurbs
  | "boolean_search"             // natural-language → boolean query
  | "bias_check"                 // JD bias rewrite (US-420)
  | "nl_talent_query"            // NL candidate search (US-379)
  | "semantic_global_search"     // cross-entity semantic search
  | "auto_tag";                  // auto-applied tags

export interface DecisionSubject {
  type: "candidate" | "job" | "match_score" | "outreach" | "shortlist"
      | "query" | "scorecard" | "interview" | "other";
  id?:  string | null;
}

export interface RecordDecisionInput {
  agencyId:  string | null | undefined;
  userId?:   string | null;
  type:      DecisionType;
  subject:   DecisionSubject;
  related?:  { type: string; id: string } | null;
  provider:  "anthropic" | "openai";
  model:     string;
  modelVersion?: string | null;
  rationale?:    string | null;
  inputPayload?: unknown;
  usageEventId?: string | null;
  /**
   * When true, surfaces in the candidate portal's transparency view
   * (assuming the agency has `ai_transparency_enabled`). Default: false.
   * Decisions that directly shape a candidate's *own* experience should
   * be true — match scoring of their profile, resume parse, outreach
   * drafted to them, shortlist inclusion. Keep recruiter-internal tools
   * (boolean_search, bias_check on a JD, auto_tag on random imports) false.
   */
  visibleToCandidate?: boolean;
}

/* ── Model card registry ──────────────────────────────────────────────── */

/**
 * Stable URLs that outlive the specific model version. When Anthropic
 * releases a new sonnet, we bump the `model` field in new decisions but
 * the card URL still resolves to "Claude Sonnet (generation 4) family
 * model card" — keeping historical decisions auditable.
 */
const MODEL_CARDS: Record<string, string> = {
  "claude-sonnet-4-6":         "https://www.anthropic.com/claude/sonnet",
  "claude-opus-4-6":           "https://www.anthropic.com/claude/opus",
  "claude-haiku-4-5-20251001": "https://www.anthropic.com/claude/haiku",
  "text-embedding-3-small":    "https://platform.openai.com/docs/guides/embeddings",
  "text-embedding-3-large":    "https://platform.openai.com/docs/guides/embeddings",
};

export function modelCardUrl(model: string): string | null {
  if (MODEL_CARDS[model]) return MODEL_CARDS[model];
  // Fallback family match so unknown minor versions still resolve.
  if (model.startsWith("claude-sonnet")) return MODEL_CARDS["claude-sonnet-4-6"];
  if (model.startsWith("claude-opus"))   return MODEL_CARDS["claude-opus-4-6"];
  if (model.startsWith("claude-haiku"))  return MODEL_CARDS["claude-haiku-4-5-20251001"];
  if (model.startsWith("text-embedding")) return MODEL_CARDS["text-embedding-3-small"];
  return null;
}

/* ── Helpers ──────────────────────────────────────────────────────────── */

/**
 * Canonical-stringify + SHA-256. Used to compute `input_hash` so that
 * admins can tell whether two decisions were produced from equivalent
 * inputs without having to store the full prompt. Accepts any JSON-safe
 * shape; keys are sorted so ordering differences don't change the hash.
 */
export function hashInput(payload: unknown): string | null {
  if (payload == null) return null;
  try {
    const canonical = canonicalStringify(payload);
    return createHash("sha256").update(canonical).digest("hex");
  } catch {
    return null;
  }
}

function canonicalStringify(v: unknown): string {
  if (v === null || typeof v !== "object") return JSON.stringify(v);
  if (Array.isArray(v)) return "[" + v.map(canonicalStringify).join(",") + "]";
  const keys = Object.keys(v as Record<string, unknown>).sort();
  return "{" + keys.map(k =>
    JSON.stringify(k) + ":" + canonicalStringify((v as Record<string, unknown>)[k])
  ).join(",") + "}";
}

/* ── Public API ───────────────────────────────────────────────────────── */

/**
 * Record an AI decision. Fire-and-forget — the returned promise resolves
 * with the decision id (or null on failure). Safe to `void`-ignore.
 */
export async function recordAiDecision(
  input: RecordDecisionInput,
): Promise<string | null> {
  if (!input.agencyId) return null; // platform-level calls aren't per-tenant decisions

  try {
    const db = createServiceClient();
    const { data, error } = await db
      .from("ai_decisions")
      .insert({
        agency_id:            input.agencyId,
        user_id:              input.userId ?? null,
        decision_type:        input.type,
        subject_type:         input.subject.type,
        subject_id:           input.subject.id ?? null,
        related_type:         input.related?.type ?? null,
        related_id:           input.related?.id   ?? null,
        provider:             input.provider,
        model:                input.model,
        model_version:        input.modelVersion ?? null,
        model_card_url:       modelCardUrl(input.model),
        rationale:            input.rationale?.slice(0, 500) ?? null,
        input_hash:           hashInput(input.inputPayload),
        usage_event_id:       input.usageEventId ?? null,
        visible_to_candidate: input.visibleToCandidate ?? false,
      })
      .select("id")
      .single();

    if (error) {
      console.error("[ai-decision-log] insert failed:", error);
      return null;
    }
    return (data as { id: string }).id;
  } catch (err) {
    // Belt-and-braces: swallow anything. Decision logging is observational.
    console.error("[ai-decision-log] unexpected error:", err);
    return null;
  }
}

/**
 * Short rationale builder — produces the 1-liner shown in the
 * transparency UI. Keeps wording consistent across call sites.
 */
export function describeDecision(type: DecisionType): string {
  switch (type) {
    case "match_score_embedding":
      return "Ranked how well a candidate's profile matches a job using vector similarity.";
    case "match_score_explain":
      return "Generated a per-criterion breakdown explaining a candidate-job match score.";
    case "resume_parse":
      return "Extracted structured fields (experience, education, skills) from a resume.";
    case "skill_normalise":
      return "Canonicalised freeform skill terms to a shared taxonomy.";
    case "candidate_summary":
      return "Wrote a 2–3 sentence summary of the candidate's profile.";
    case "candidate_outreach":
      return "Drafted an outreach message to the candidate.";
    case "interview_questions":
      return "Generated suggested interview questions for this candidate and role.";
    case "shortlist_compile":
      return "Produced a ranked shortlist with per-candidate summaries.";
    case "boolean_search":
      return "Translated natural language to a boolean recruiter search.";
    case "bias_check":
      return "Flagged potentially biased wording in a job description and suggested rewrites.";
    case "nl_talent_query":
      return "Interpreted a natural-language query and searched the candidate database.";
    case "semantic_global_search":
      return "Performed a semantic search across candidates, jobs, and companies.";
    case "auto_tag":
      return "Suggested or applied tags to a record based on its content.";
  }
}
