/**
 * GET  /api/sending-domains   — list domains for this agency
 * POST /api/sending-domains   — add a new domain (initiates verification)
 * DELETE /api/sending-domains — remove a domain
 *
 * US-471: Custom sending domain SPF/DKIM/DMARC verification flow.
 */

import { NextRequest, NextResponse }  from "next/server";
import { createClient }               from "@/lib/supabase/server";
import { getAgencyContext }            from "@/lib/supabase/agency-cache";
import { checkCsrf }                  from "@/lib/csrf";

// ── GET ───────────────────────────────────────────────────────────────────────

export async function GET(req: NextRequest) {
  void req;
  const supabase = await createClient();
  const ctx      = await getAgencyContext(supabase);
  if (!ctx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data, error } = await supabase
    .from("sending_domains")
    .select("id, domain, verified, verified_at, spf_record, dkim_selector, dkim_public_key, dmarc_record, provider, created_at")
    .eq("agency_id", ctx.agencyId)
    .order("created_at", { ascending: false });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ domains: data ?? [] });
}

// ── POST ──────────────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const csrfError = checkCsrf(req);
  if (csrfError) return csrfError;

  const supabase = await createClient();
  const ctx      = await getAgencyContext(supabase);
  if (!ctx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json().catch(() => ({})) as { domain?: string };
  const raw  = (body.domain ?? "").trim().toLowerCase();

  // Basic domain validation
  if (!raw || !/^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$/.test(raw)) {
    return NextResponse.json({ error: "Invalid domain format" }, { status: 400 });
  }

  // Generate DKIM selector and key pair stub
  // In production these would be generated by the email provider (Postmark/SendGrid)
  // and returned from their domain registration API. We store the required DNS records.
  const dkimSelector = "mail";
  const spfRecord    = `v=spf1 include:spf.postmarkapp.com ~all`;
  const dmarcRecord  = `v=DMARC1; p=none; rua=mailto:dmarc@${raw}`;

  const { data, error } = await supabase
    .from("sending_domains")
    .insert({
      agency_id:    ctx.agencyId,
      domain:       raw,
      spf_record:   spfRecord,
      dkim_selector: dkimSelector,
      dkim_public_key: null,  // Populated after provider creates the domain
      dmarc_record: dmarcRecord,
      provider:     "postmark",
    })
    .select()
    .single();

  if (error) {
    if (error.code === "23505") {
      return NextResponse.json({ error: "Domain already added" }, { status: 409 });
    }
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({ domain: data }, { status: 201 });
}

// ── DELETE ────────────────────────────────────────────────────────────────────

export async function DELETE(req: NextRequest) {
  const csrfError = checkCsrf(req);
  if (csrfError) return csrfError;

  const supabase = await createClient();
  const ctx      = await getAgencyContext(supabase);
  if (!ctx) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { searchParams } = new URL(req.url);
  const id = searchParams.get("id");
  if (!id) return NextResponse.json({ error: "id is required" }, { status: 400 });

  const { error } = await supabase
    .from("sending_domains")
    .delete()
    .eq("id", id)
    .eq("agency_id", ctx.agencyId);  // RLS double-check

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });
  return NextResponse.json({ ok: true });
}
